### ISSUE TITLE
Missing. Add some counts

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/earthcube_utilities#77]
How many items are in the missing: 

```
"graph_urn_count": 27346,
  "missing_summon_graph": [
    "000646df9efad9f0d0a9a38ea
"summoned_count": 37704,
  "missing_sitemap_summon": 
  
```
  so add:
missing_summon_graph_count
missing_sitemap_summon_count

Sometimes the run stats are a bit different. 

```
RunStats:
  Start: 2023-04-22 18:10:27.176264344 +0000 UTC m=+0.510716267
  Repositories:
    - name: r2r
      SitemapIssues: 2054
      SitemapCount: 48425
      SitemapStored: 92582
 100% |██████████████████████████████████████████████████████████████| (37704/37704, 56 it/s)
```

Also add some counts to the data returned by the reports:

```
{
            "report": "type_count",
             "count": 9999,
            "data": [
                {

```
